### ISSUE TITLE
Windmill issues

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [bartimaeusnek/bartworks#1]
The grindstone top and bottom half recipes do not oredict for smoothstone and granite from different mods.

The windmill recipes do not show up in NEI.

If altitude increases processing speed it would be good to put this in the tooltip.

**Comment by bartimaeusnek** [comment]
The windmill recipes do not show up in NEI, because its a Macerator that doesn't have a different recipe map.

oredicted to "stone","stoneSmooth" for stone and "blockGranite","stoneGranite","Granite","granite" for granite is done, tooltip adjustments are done too.
