### ISSUE TITLE
Wax Capsule Lava (Disabling? Making work? Whichever)

### ISSUE THREAD

**Issue by Prometheus0000** [bartimaeusnek/bartworks#103]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5194

**Comment by Prometheus0000** [comment]
Also see 'wax capsule filled with water give ice capsule', https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5610

**Comment by bartimaeusnek** [comment]
already fixed
