### ISSUE TITLE
crash during launch

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [bartimaeusnek/bartworks#23]
https://pastebin.com/x4TDQh1Q

This also occurs with 5.09.32pre5. It occurs with both bartworks 0.4.8 releases but not 0.4.5.

**Comment by bartimaeusnek** [comment]
should be fixed, please re-try with v0.4.9 and make sure, that you do not have a modified version of GT. the GTNH fork works fine, aswell as the original 5.09.31.
