### ISSUE TITLE
BioData localization request

### ISSUE THREAD

**Issue by lycc193** [bartimaeusnek/bartworks#38]
I am a Chinese player at GTNH.

GTNH Version : 2.0.7.5
Bartworks Version : 0.4.16

Some fluids in bartworks cannot be localization
And there is no space to do the split, very unsightly.
![QQ图片20190928234804](https://user-images.githubusercontent.com/25812011/65819120-87c88200-e24b-11e9-8602-7a610aff5ce6.png)

**Comment by bartimaeusnek** [comment]
newest beta (0.5.2_pre14) fixes this, you can add localisation to the GT Language file now if you like.

**Comment by lycc193** [comment]
The fluid in ```FluidLoader.BioLabFluidMaterials``` also cannot be localization.
And cannot be used for subsequent recipes.
