### ISSUE TITLE
NEI recipe crash

### ISSUE THREAD

**Issue by inklesspen1scripter** [bartimaeusnek/bartworks#42]
Minecraft 1.7.10
Bartworks 0.5.2
GT 5 Unofficial 5.09.31
CodeChickenCore-1.7.10-1.0.7.47-universal
NotEnoughItems-1.7.10-1.0.5.120-universal
NEIIntegration-MC1.7.10-1.1.2

When I open recipe of any ore from this mode and try to open all recipes game crashes
[crash-2019-12-12_18.19.06-client.txt](https://github.com/bartimaeusnek/bartworks/files/3956450/crash-2019-12-12_18.19.06-client.txt)

**Comment by bartimaeusnek** [comment]
bartworks is currently in beta and 0.5.2 is pretty old, try this pre version please:
https://cdn.discordapp.com/attachments/600644699770060821/654477751704616964/bartworks1.7.10-0.5.3_pre1.jar

**Comment by Prometheus0000** [comment]
Still crashes with GTNH 2.0.8.5dev with bartworks.1.7.10.-0.5.10.jar. Tried left clicking on the last small ore, crash: 
[crash-2020-03-02_13.03.20-client.txt](https://github.com/bartimaeusnek/bartworks/files/4277105/crash-2020-03-02_13.03.20-client.txt)
