### ISSUE TITLE
Mega Vacuum Freezer don't need top and bottom layer

### ISSUE THREAD

**Issue by pulsemageadvocate** [bartimaeusnek/bartworks#45]
GTNH Version : 2.0.7.5
Bartworks Version : 0.4.16,0.5.2,0.5.3_pre1

![20191222_70](https://user-images.githubusercontent.com/59131259/71317443-8f06d100-24c4-11ea-9629-09fc87bd3446.jpg)
It works.
And hatches in top or bottom layer don't work.

**Comment by bartimaeusnek** [comment]
known, fixed.
