### ISSUE TITLE
Client crash when viewing ores

### ISSUE THREAD

**Issue by fireaid** [bartimaeusnek/bartworks#46]
[crash-2019-12-29_16.12.50-client.txt](https://github.com/bartimaeusnek/bartworks/files/4008064/crash-2019-12-29_16.12.50-client.txt)
What could have gone wrong?

**Comment by bartimaeusnek** [comment]
Youre using an old version or not the GTNH fork of Galactic Greg, aparently

**Comment by bartimaeusnek** [comment]
should be fixed

**Comment by yukieiji** [comment]
This issue occurred in GTNH ver2.0.8.3 (bartworks.1.7.10.-0.5.10)
Game crashed when looking at Temagamite Ore distribution
[crash-2020-01-19_03.22.26-client.txt](https://github.com/bartimaeusnek/bartworks/files/4081386/crash-2020-01-19_03.22.26-client.txt)

**Comment by Dream-Master** [comment]
@bartimaeusnek
