### ISSUE TITLE
Idea of Platinum metal processing

### ISSUE THREAD

**Issue by NanamiArihara** [bartimaeusnek/bartworks#61]
Current processing of Platinum metal are too complicated and unworthy, in order to make things more like real life, we find the real refining diagram here:
![-55536877638ac73d](https://user-images.githubusercontent.com/6669365/77554260-d00de780-6ef0-11ea-82fe-27f95cadc720.jpg)
Hope this can be implemented and replace the current one soon.

**Comment by NanamiArihara** [comment]
This is extracted from _Chemistry of the Elements Second Edition_
May this Mod be closer to reality and really fun

**Comment by bartimaeusnek** [comment]
This process is a Lab Method youre suggesting. Its not really compareable as to the current one which is re-created from the actual industry standart of how platinum (and side metals) are fabricated in large scale.
