### ISSUE TITLE
Windmill stops working when there is a second windmill in the chunk next to it

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [bartimaeusnek/bartworks#90]
Our windmill stopped working after we built a second windmill in the neighbouring chunk. Breaking the primitive kinetic shaft box in any one of the windmills will make the other windmill function properly instantly. Placing it back makes the other windmill stop again.

Is this intentional? And if it is intensional could we maybe have a note on this in the tooltip?

**Comment by GeicowithaBango** [comment]
Yes this is intentional, the kinetic shaft box works like the normal one from ic2 (and its derivatives).

**Comment by AndrewAmmerlaan** [comment]
> Yes this is intentional, the kinetic shaft box works like the normal one from ic2 (and its derivatives).

aah right, I read up on the ic2 rotors and now it all makes sense, thanks

**Comment by AndrewAmmerlaan** [comment]
![2020-07-25_16 45 11](https://user-images.githubusercontent.com/8460628/88459546-87fad380-ce96-11ea-85d5-069bdb52d3ff.png)

working perfectly now :smile:
