### ISSUE TITLE
The LV Crop Gene extractor appears to be using MV power amount, so it fails unless supplied with extra amps

### ISSUE THREAD

**Issue by Prometheus0000** [bartimaeusnek/bartworks#93]
![image](https://user-images.githubusercontent.com/8517039/93011911-115e8600-f569-11ea-8aa4-aba58657379a.png)
And yes, this is the LV device. It does run if you supply it with enough power.

**Comment by bartimaeusnek** [comment]
LV Crop Gene extractor isnt a bartworks machine.
